Simulation and Modeling Lab  
**Course Code:** CSE 413  
**Academic Level/Term:** 4/1  
**Credit Hour:** 3  
**Course Teacher:** Audity Ghosh, Lecturer, Department of Computer Science and Engineering, University of Information Technology and Sciences (UITS)  
**Date:** 21 July, 2025  


### What is Simulation and Modeling?

**Simulation and modeling** are essential techniques used to understand, predict, and improve the behavior of complex systems (mathematical models). In **modeling**, you create a simplified version of a system—like a blueprint or map—that represents its key components. In **simulation**, you run experiments with that model to observe how it behaves over time under various conditions.

For example, **in a traffic management system**, you might model how cars flow through an intersection, and then simulate what happens during rush hour or in the case of an accident. Instead of testing the system in real life (which could be dangerous or costly), you can test it using **Python** simulations.

### Why Should You Take This Simulation and Modeling Course?

This course teaches you how to apply simulation and modeling techniques using **Python**—one of the most popular programming tools in academia and industry. You’ll gain practical skills that are useful for:
- **Modeling real-world systems** (e.g., network traffic, AI algorithms).
- **Running simulations** to test and optimize those models before real-world application.
- **Solving engineering problems** in computer science, software development, and data analysis.

Whether you’re working on **thesis projects** or **real-world applications**, you will learn how to apply these tools in practical scenarios that will make you stand out in the job market.

---

### Course Breakdown with Real-Life Examples (Using Python):

1. **Introduction to Python: Basic Operations and Functions**  
   - **Example**: Suppose you're building a **robotic control system**. You’ll need to use Python to control the robot’s movements, calculate angles, and manage sensor inputs.
   - **Python**: Learn basic operations like addition, multiplication, and handling matrices, which are crucial for engineering and simulation tasks in Python.

2. **Random Number Generation and Testing**  
   - **Example**: In a **gaming app**, you may need to generate random events (like dice rolls or random card shuffling). This session teaches how to create random numbers in Python and test their distribution for fairness.
   - **Python**: You will use built-in functions like `numpy.random` to generate random numbers.

3. **Hypothesis Testing (One-Sample t-Test)**  
   - **Example**: You're working on a **data science project** to determine whether a new marketing strategy has increased customer engagement. You’ll use the **one-sample t-test** to analyze data before and after the campaign.
   - **Python**: Perform t-tests using Python’s `scipy.stats.ttest_1samp` to evaluate whether your sample data shows a statistically significant difference.

4. **Two-Sample t-Test in Python**  
   - **Example**: You want to compare the performance of two **machine learning algorithms** on different datasets. Use the **two-sample t-test** to determine if one algorithm significantly outperforms the other.
   - **Python**: You can implement this in Python with `scipy.stats.ttest_ind`.

5. **Chi-Square Goodness-of-Fit Test**  
   - **Example**: In **data science**, you want to check if the observed distribution of customer purchases matches a predicted distribution. You use the **Chi-Square test** to compare the actual data to your model.
   - **Python**: In Python, `scipy.stats.chisquare` will help you test the goodness-of-fit.

6. **Performing Chi-Square Test in Python**  
   - **Example**: Suppose you're working on **healthcare analytics** to test if the distribution of disease cases follows an expected pattern across different regions. You would perform the Chi-Square test in Python.
   - **Python**: Learn how to perform the Chi-Square test in Python using `scipy.stats.chisquare`.

7. **One-Sample Kolmogorov-Smirnov Test**  
   - **Example**: If you're analyzing **financial data** and want to check if it follows a **normal distribution**, you can use the **Kolmogorov-Smirnov test** in Python.
   - **Python**: This test can be done using `scipy.stats.kstest` in Python.

8. **Two-Sample Kolmogorov-Smirnov Test**  
   - **Example**: You might compare the **performance** of two different **web servers** under similar traffic loads. The two-sample Kolmogorov-Smirnov test can help determine if the performance data of both servers is significantly different.
   - **Python**: In Python, use `scipy.stats.ks_2samp`.

9. **Testing Normality (Standard Normal Distribution)**  
   - **Example**: You’re analyzing **sensor data** from a robotics system and need to verify whether it follows a **normal distribution** to apply certain statistical models.
   - **Python**: Use Python’s `scipy.stats.normaltest` to perform normality tests.

10. **Project Distribution: Your Task to Submit before Finals, Create Groups of 3-4 people, Generate Ideas, Share Idea Proposal in Proper Format in Week 4**  
   - **Example**: If you're building a **distributed system** for a cloud-based application, you’ll need to simulate how data is distributed across multiple servers and ensure even load balancing.
   - **Python**: Model the distribution of tasks across servers and analyze the distribution patterns using Python.

11. **Implementation of Monte Carlo Simulation**  
   - **Example**: In **finance**, you might simulate future stock prices using **Monte Carlo simulations** to assess risks or returns of a portfolio.
   - **Python**: Learn how to implement Monte Carlo simulations in Python, using Python’s `numpy.random` for random sampling.

12. **Single Server Queuing System**  
   - **Example**: Suppose you're designing a **customer support system** where customers wait in a queue for help. You can model this **single-server queuing system** to optimize agent availability.
   - **Python**: Simulate and optimize the queuing process using Python libraries like `queueing` or custom scripts.

13. **Complex Engineering Problem**  
   - **Example**: You’re tasked with designing a **robotic arm** for industrial use. The problem requires multiple simulations, including motor behavior, arm movement, and task efficiency.
   - **Python**: Using Python, you will create simulations to optimize the design of the robotic arm and test it under various conditions.

---

### Why This Course is Valuable:

- **Real-World Skills**: By using **Python**, you’ll gain versatile skills that can be applied to a wide range of problems, from software testing to complex engineering simulations.
- **Career Benefits**: Mastering **simulation and modeling** will make you a highly sought-after candidate in industries like **data science**, **AI development**, **network design**, and **engineering**.
- **Project and Thesis Work**: Whether you're working on a **thesis** or **personal projects**, the course will help you use simulations to validate your ideas and predictions before applying them in real life.

In this course, you’ll not only learn to model and simulate complex systems but also gain the confidence to apply these techniques in **Python** to solve real-world problems in computer science and engineering.


**What is Simulation and Modeling?**
Imagine you're designing a new traffic light system for a busy city. You don’t want to test it directly on real streets because that would disrupt traffic and cause potential accidents. Instead, you use simulation and modeling to create a virtual version of the system and test it digitally before applying it in the real world.

Modeling in this case means creating a simplified version of the traffic system. For example, you create a model that represents traffic flow, car speeds, and light changes over time.

Simulation is running that model over a set period to see how traffic behaves under different conditions. You can test things like "What happens if there’s an accident on one road?" or "How does the system perform during rush hour?" without actually stopping traffic.

By using simulation and modeling, you can test many different scenarios without risk or cost and optimize the traffic system for the best performance before implementing it in real life.

# Necessary Libraries

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Scaler and Built In Functions

In [ ]:
# Sample scalar and array inputs
scalar = 2.5
arr = np.array([1, 2, 3, 4, 5])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
asin: [0.20135792 0.41151685 0.64350111 0.92729522 1.57079633]
acos: [1.36943841 1.15927948 0.92729522 0.64350111 0.        ]
atan: [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077]
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
abs: [1 2 3 4 5]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]
rem: [1 0 1 0 1]
round: [1 2 3 4 5]
floor: [1. 2. 3. 4. 5.]
ceil: [1. 2. 3. 4. 5.]


## Do it For 2X2 matrix

In [ ]:
# Creating a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1 2]
 [3 4]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]

asine:
 [[0.25268026 0.52359878]
 [0.84806208 1.57079633]]

acosine:
 [[1.31811607 1.04719755]
 [0.72273425 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]]

exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]]

abs:
 [[1 2]
 [3 4]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]]

floor:
 [[1. 2.]
 [3. 4.]]

ceil:
 [[1. 2.]
 [3. 4.]]


### To Students: Do the same for 3*2 matrix

# Vector Functions

In [ ]:
# Sample vector (1D array)
vec = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 9 at index 5
Min value: 1 at index 1
Length of vector: 8
Sorted vector: [1 1 2 3 4 5 6 9]
Sum of elements: 31
Product of elements: 6480
Median value: 3.5
Mean value: 3.875
Standard deviation: 2.5708704751503917


### To Students: Do the same for 2*3 matrix, what about descending sort within rows or in total matrix? What about using floating numbers?